/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import ConexionPGadmin.Conexion;
import ConexionPGadmin.GeneradorFacturaPDF;
import Logica.Administrador;
import java.sql.SQLException;
import java.sql.*;

/**
 *
 * @author Arana
 */
public class Form_Boleta extends javax.swing.JFrame {

    Administrador admin = new Administrador();

    /**
     * Creates new form Form_Boleta
     */
    public Form_Boleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ID_MESA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Boton_Observar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Ordenes_Totales = new javax.swing.JTable();
        Boton_Comprobante = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();
        Boton_Retorno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("FINALIZACION DE COMPRA");

        ID_MESA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_MESAActionPerformed(evt);
            }
        });

        jLabel2.setText("MESA");

        Boton_Observar.setText("Observar");
        Boton_Observar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ObservarActionPerformed(evt);
            }
        });

        Tabla_Ordenes_Totales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Ordenes_Totales);

        Boton_Comprobante.setText("Comprobante");
        Boton_Comprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ComprobanteActionPerformed(evt);
            }
        });

        jLabel3.setText("Total:");

        LabelTotal.setText("MESA");

        Boton_Retorno.setText("RETORNO");
        Boton_Retorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_RetornoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(ID_MESA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Boton_Observar))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(Boton_Comprobante))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(LabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Boton_Retorno)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ID_MESA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Observar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(LabelTotal))
                        .addGap(38, 38, 38)
                        .addComponent(Boton_Comprobante)))
                .addGap(18, 18, 18)
                .addComponent(Boton_Retorno)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_ObservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ObservarActionPerformed
        // TODO add your handling code here:
        Tabla_Ordenes_Totales.setModel(admin.observarordenesregistro(Integer.parseInt(ID_MESA.getText())));
        Double valor = totalpedido(Integer.parseInt(ID_MESA.getText()));
        LabelTotal.setText(String.valueOf(valor));

    }//GEN-LAST:event_Boton_ObservarActionPerformed

    private void ID_MESAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_MESAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_MESAActionPerformed

    private void Boton_ComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ComprobanteActionPerformed
        // TODO add your handling code here:
        // Obtener nombre completo
        String sql = "select nombre, apellido_paterno, apellido_materno from verclientes where id_mesa = ?";
        String nombrecompleto = "";

        try (Connection conn = Conexion.getConexion(); PreparedStatement stmt = conn.prepareCall(sql)) {

            stmt.setInt(1, Integer.parseInt(ID_MESA.getText()));

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    nombrecompleto = rs.getString("nombre") + " "
                            + rs.getString("apellido_paterno") + " "
                            + rs.getString("apellido_materno");
                }
            }
        } catch (SQLException e) {
            System.out.println("Mensaje: " + e.getMessage());
        }

// Contar cuántas órdenes hay
        String sql11 = "select nombre, precio from verordenes where id_mesa = ?";
        int filas = 0;

        try (Connection conn = Conexion.getConexion(); PreparedStatement stmt = conn.prepareCall(sql11)) {

            stmt.setInt(1, Integer.parseInt(ID_MESA.getText()));

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    filas++;
                }
            }
        } catch (SQLException e) {
            System.out.println("Error al contar órdenes: " + e.getMessage());
        }

// Declarar arreglos y llenarlos
        String[] productos = new String[filas];
        double[] precios = new double[filas];

        try (Connection conn = Conexion.getConexion(); PreparedStatement stmt = conn.prepareCall(sql11)) {

            stmt.setInt(1, Integer.parseInt(ID_MESA.getText()));

            try (ResultSet rs = stmt.executeQuery()) {
                int i = 0;
                while (rs.next()) {
                    productos[i] = rs.getString("nombre");
                    precios[i] = rs.getDouble("precio");
                    i++;
                }
            }
        } catch (SQLException e) {
            System.out.println("Error al llenar arreglos: " + e.getMessage());
        }

// Llamar a la función del PDF
        GeneradorFacturaPDF.generarFactura(nombrecompleto, productos, precios, Double.parseDouble(LabelTotal.getText()));

    }//GEN-LAST:event_Boton_ComprobanteActionPerformed

    private void Boton_RetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_RetornoActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_Boton_RetornoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Comprobante;
    private javax.swing.JButton Boton_Observar;
    private javax.swing.JButton Boton_Retorno;
    private javax.swing.JTextField ID_MESA;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JTable Tabla_Ordenes_Totales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
        private double totalpedido(int id_mesa) {
        double valor = 0;
        String sql = "select total_pedido_f(?) as total";
        try (Connection conn = Conexion.getConexion(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, id_mesa);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                valor = rs.getDouble("total");
            }

        } catch (SQLException e) {
            System.out.println("Mensaje: " + e.getMessage());

        }
        return valor;
    }
}
