/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import ConexionPGadmin.Conexion;
import Logica.Administrador;
import Logica.Bebidas;
import Logica.Observable;
import Logica.Segundos;
import Logica.Sopas;
import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arana
 */
public class FormMenu_Administrador extends javax.swing.JFrame {

    Administrador admin = new Administrador();

    /**
     * Creates new form Menu
     */
    public FormMenu_Administrador() {
        initComponents();
        TablaMenu.setModel(Observable.vermenu());
        autocompletarID();
        TablaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = TablaMenu.rowAtPoint(evt.getPoint());
                if (fila >= 0) {
                    String id = TablaMenu.getValueAt(fila, 0).toString();
                    String plato = TablaMenu.getValueAt(fila, 1).toString();
                    String precio = TablaMenu.getValueAt(fila, 3).toString();
                    ID_Producto.setText(id);
                    Nombre_Producto.setText(plato);
                    Precio_Producto.setText(precio);

                    //Field_Mesa_Activar_Pedido.setText(mesa);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMenu = new javax.swing.JTable();
        Boton_sopas = new javax.swing.JButton();
        BotonMenu = new javax.swing.JButton();
        Boton_segundos = new javax.swing.JButton();
        Boton_bebidas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonAgregarProducto = new javax.swing.JButton();
        BotonEliminarProducto = new javax.swing.JButton();
        BotonCambiarProducto = new javax.swing.JButton();
        Lista_Tipo_Producto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombre_Producto = new javax.swing.JTextField();
        Precio_Producto = new javax.swing.JTextField();
        ID_Producto = new javax.swing.JTextField();
        Boton_Retorno = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Plato", "Tipo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaMenu);

        Boton_sopas.setText("Mostrar Sopas");
        Boton_sopas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_sopasActionPerformed(evt);
            }
        });

        BotonMenu.setText("MostrarMenu");
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });

        Boton_segundos.setText("Mostrar Segundos");
        Boton_segundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_segundosActionPerformed(evt);
            }
        });

        Boton_bebidas.setText("Mostrar Bebidas");
        Boton_bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_bebidasActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Producto");

        jLabel2.setText("ID");

        BotonAgregarProducto.setText("Agregar");
        BotonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarProductoActionPerformed(evt);
            }
        });

        BotonEliminarProducto.setText("Eliminar");
        BotonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarProductoActionPerformed(evt);
            }
        });

        BotonCambiarProducto.setText("Cambiar");
        BotonCambiarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCambiarProductoActionPerformed(evt);
            }
        });

        Lista_Tipo_Producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sopa", "Segundo", "Bebida" }));

        jLabel3.setText("Tipo");

        jLabel4.setText("Precio");

        Precio_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_ProductoActionPerformed(evt);
            }
        });

        ID_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_ProductoActionPerformed(evt);
            }
        });

        Boton_Retorno.setText("RETORNO");
        Boton_Retorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_RetornoActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BotonMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Boton_segundos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Boton_bebidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Boton_sopas, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ID_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lista_Tipo_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Precio_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(BotonAgregarProducto)
                        .addGap(44, 44, 44)
                        .addComponent(BotonEliminarProducto)
                        .addGap(45, 45, 45)
                        .addComponent(BotonCambiarProducto)
                        .addGap(56, 56, 56)
                        .addComponent(Limpiar)))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Boton_Retorno)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Boton_sopas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Boton_segundos)
                        .addGap(18, 18, 18)
                        .addComponent(Boton_bebidas)
                        .addGap(18, 18, 18)
                        .addComponent(BotonMenu)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Lista_Tipo_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(Nombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Precio_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ID_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonAgregarProducto)
                            .addComponent(BotonEliminarProducto)
                            .addComponent(BotonCambiarProducto)
                            .addComponent(Limpiar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(Boton_Retorno)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarProductoActionPerformed
        try {
            autocompletarID();
            agregarproductos();
            JOptionPane.showMessageDialog(null,"Insercion Exitosa");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Agregar Producto " + e);
        }
        TablaMenu.setModel(Observable.vermenu());
    }//GEN-LAST:event_BotonAgregarProductoActionPerformed

    private void Boton_bebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_bebidasActionPerformed
        // TODO add your handling code here:
        TablaMenu.setModel(admin.verBebidas());
    }//GEN-LAST:event_Boton_bebidasActionPerformed

    private void Boton_segundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_segundosActionPerformed
        // TODO add your handling code here:
        TablaMenu.setModel(admin.verSegundos());
    }//GEN-LAST:event_Boton_segundosActionPerformed

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        // TODO add your handling code here:
        TablaMenu.setModel(Observable.vermenu());
    }//GEN-LAST:event_BotonMenuActionPerformed

    private void Boton_sopasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_sopasActionPerformed
        TablaMenu.setModel(admin.verSopas());
    }//GEN-LAST:event_Boton_sopasActionPerformed

    private void Precio_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_ProductoActionPerformed

    private void BotonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarProductoActionPerformed
        // TODO add your handling code here:
        try {
            eliminarproductos();
            
            JOptionPane.showMessageDialog(null,"Eliminacion Exitosa");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar Producto " + e);
        }
        TablaMenu.setModel(Observable.vermenu());

    }//GEN-LAST:event_BotonEliminarProductoActionPerformed

    private void BotonCambiarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCambiarProductoActionPerformed
        // TODO add your handling code here:
        try {
            actualizarproductos();
            JOptionPane.showMessageDialog(null,"Actualizacion Exitosa");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Actualizar Producto " + e);
        }
        TablaMenu.setModel(Observable.vermenu());

    }//GEN-LAST:event_BotonCambiarProductoActionPerformed

    private void Boton_RetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_RetornoActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_Boton_RetornoActionPerformed

    private void ID_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_ProductoActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        Nombre_Producto.setText("");
        Precio_Producto.setText("");
        autocompletarID();

    }//GEN-LAST:event_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void mostrarMenu() {
        TablaMenu.setModel(Observable.vermenu());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarProducto;
    private javax.swing.JButton BotonCambiarProducto;
    private javax.swing.JButton BotonEliminarProducto;
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton Boton_Retorno;
    private javax.swing.JButton Boton_bebidas;
    private javax.swing.JButton Boton_segundos;
    private javax.swing.JButton Boton_sopas;
    private javax.swing.JTextField ID_Producto;
    private javax.swing.JButton Limpiar;
    private javax.swing.JComboBox<String> Lista_Tipo_Producto;
    private javax.swing.JTextField Nombre_Producto;
    private javax.swing.JTextField Precio_Producto;
    private javax.swing.JTable TablaMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void agregarproductos() {
        String valor = (String) Lista_Tipo_Producto.getSelectedItem();
        if (valor.contains("Segundo")) {
            Segundos s = new Segundos(Nombre_Producto.getText(),
                    Double.parseDouble(Precio_Producto.getText()),
                    Integer.parseInt(ID_Producto.getText()));
            admin.agregarSegundos(s);

        } else if (valor.contains("Sopa")) {
            Sopas so = new Sopas(Nombre_Producto.getText(),
                    Double.parseDouble(Precio_Producto.getText()),
                    Integer.parseInt(ID_Producto.getText()));
            admin.agregarSopas(so);
        } else if (valor.contains("Bebida")) {
            Bebidas be = new Bebidas(Nombre_Producto.getText(),
                    Double.parseDouble(Precio_Producto.getText()),
                    Integer.parseInt(ID_Producto.getText()));
            admin.agregarBebidas(be);
        }

    }

    private void eliminarproductos() {
        String valor = (String) Lista_Tipo_Producto.getSelectedItem();
        if (valor.contains("Segundo")) {
            admin.eliminarSegundos(Integer.parseInt(ID_Producto.getText()));

        } else if (valor.contains("Sopa")) {
            admin.eliminarSopas(Integer.parseInt(ID_Producto.getText()));
        } else if (valor.contains("Bebida")) {

            admin.eliminarBebidas(Integer.parseInt(ID_Producto.getText()));
        }

    }

    private void actualizarproductos() {
        String valor = (String) Lista_Tipo_Producto.getSelectedItem();
        if (valor.contains("Segundo")) {
            Segundos s = new Segundos(Nombre_Producto.getText(),
                    Double.parseDouble(Precio_Producto.getText()),
                    Integer.parseInt(ID_Producto.getText()));
            admin.actualizarSegundos(s, valor);

        } else if (valor.contains("Sopa")) {
            Sopas so = new Sopas(Nombre_Producto.getText(),
                    Double.parseDouble(Precio_Producto.getText()),
                    Integer.parseInt(ID_Producto.getText()));
            admin.actualizarSopas(so, valor);
        } else if (valor.contains("Bebida")) {
            Bebidas be = new Bebidas(Nombre_Producto.getText(),
                    Double.parseDouble(Precio_Producto.getText()),
                    Integer.parseInt(ID_Producto.getText()));
            admin.actualizarBebidas(be, valor);
        }

    }

    private void autocompletarID() {
        String sql = "SELECT COALESCE(MAX(id_producto), 0) + 1 AS siguiente_id FROM productos"; // Reemplaza "productos" con tu tabla

        try (Connection conn = Conexion.getConexion(); PreparedStatement stmt = conn.prepareStatement(sql); ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                int siguienteID = rs.getInt("siguiente_id");
                ID_Producto.setText(String.valueOf(siguienteID));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al obtener ID desde la base de datos: " + e.getMessage());
        }
    }

}
