/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import ConexionPGadmin.Api_Dni;
import ConexionPGadmin.Conexion;
import Logica.Administrador;
import Logica.Cliente;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.*;

/**
 *
 * @author Arana
 */
public class Form_Clientes extends javax.swing.JFrame {

    Api_Dni api = new Api_Dni();
    Administrador admin = new Administrador();
    Form_Mesas_Clientes mesas = new Form_Mesas_Clientes();

    /**
     * Creates new form Form_Clientes
     */
    public Form_Clientes() {
        initComponents();
        Tabla_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = Tabla_Clientes.rowAtPoint(evt.getPoint());
                if (fila >= 0) {
                    String dni = Tabla_Clientes.getValueAt(fila, 0).toString();
                    String mesa = Tabla_Clientes.getValueAt(fila, 4).toString();
                    Field_DNI.setText(dni);
                    Field_Mesa_ID.setText(mesa);
                    //Field_Mesa_Activar_Pedido.setText(mesa);
                }
            }
        });
        
        DefaultTableModel modelo = (DefaultTableModel) admin.observarclientes();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        Tabla_Clientes.setRowSorter(sorter);

        Field_DNI.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { buscar(); }
            @Override
            public void removeUpdate(DocumentEvent e) { buscar(); }
            @Override
            public void changedUpdate(DocumentEvent e) { buscar(); }

            void buscar() {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + Field_DNI.getText()));
            }
        });
        
        
        Tabla_Clientes.setModel(admin.observarclientes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Field_DNI = new javax.swing.JTextField();
        Boton_Insertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Clientes = new javax.swing.JTable();
        Mensaje_Error_Cliente = new javax.swing.JLabel();
        Listar_Registrar_Cliente = new javax.swing.JButton();
        Boton_Buscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Field_Mesa_ID = new javax.swing.JTextField();
        Boton_Asignar_Mesa = new javax.swing.JButton();
        Boton_Mesa_RegistrarCliente = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        Mensaje_Error_ActivarPedido = new javax.swing.JLabel();
        Boton_Retorno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("MENU CLIENTE");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel3.setText("DNI");

        Field_DNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_DNIActionPerformed(evt);
            }
        });

        Boton_Insertar.setText("Insertar");
        Boton_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_InsertarActionPerformed(evt);
            }
        });

        Tabla_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "A. Paterno", "A. Materno", "Mesa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_Clientes);
        if (Tabla_Clientes.getColumnModel().getColumnCount() > 0) {
            Tabla_Clientes.getColumnModel().getColumn(0).setResizable(false);
            Tabla_Clientes.getColumnModel().getColumn(1).setResizable(false);
            Tabla_Clientes.getColumnModel().getColumn(2).setResizable(false);
            Tabla_Clientes.getColumnModel().getColumn(3).setResizable(false);
            Tabla_Clientes.getColumnModel().getColumn(4).setResizable(false);
        }

        Listar_Registrar_Cliente.setText("Listar");
        Listar_Registrar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_Registrar_ClienteActionPerformed(evt);
            }
        });

        Boton_Buscar.setText("Buscar");
        Boton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BuscarActionPerformed(evt);
            }
        });

        jLabel5.setText("MESA");

        Boton_Asignar_Mesa.setText("Asignar");
        Boton_Asignar_Mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Asignar_MesaActionPerformed(evt);
            }
        });

        Boton_Mesa_RegistrarCliente.setText("Ver Mesas");
        Boton_Mesa_RegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Mesa_RegistrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Boton_Mesa_RegistrarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Listar_Registrar_Cliente)
                .addGap(55, 55, 55))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Field_DNI, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(Field_Mesa_ID))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Boton_Insertar)
                                .addGap(40, 40, 40)
                                .addComponent(Boton_Buscar))
                            .addComponent(Boton_Asignar_Mesa)))
                    .addComponent(Mensaje_Error_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Field_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Insertar)
                    .addComponent(Boton_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Field_Mesa_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Asignar_Mesa))
                .addGap(18, 18, 18)
                .addComponent(Mensaje_Error_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Listar_Registrar_Cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(Boton_Mesa_RegistrarCliente)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("REGISTRAR CLIENTE", jDesktopPane1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Mensaje_Error_ActivarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(Mensaje_Error_ActivarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        jDesktopPane2.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", jDesktopPane2);

        Boton_Retorno.setText("RETORNO");
        Boton_Retorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_RetornoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Boton_Retorno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Boton_Retorno)
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_RetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_RetornoActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_Boton_RetornoActionPerformed

    private void Boton_Mesa_RegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Mesa_RegistrarClienteActionPerformed
        // TODO add your handling code here:
        mesas.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mesas.setVisible(true);
        mesas.setEnabled(true);
    }//GEN-LAST:event_Boton_Mesa_RegistrarClienteActionPerformed

    private void Boton_Asignar_MesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Asignar_MesaActionPerformed
        try {
            int val = Integer.parseInt(Field_Mesa_ID.getText());
            admin.asignarmesa(Integer.parseInt(Field_Mesa_ID.getText()), Integer.parseInt(Field_DNI.getText()), Mensaje_Error_Cliente);
            String sql = "select id_mesa from clientes where id_mesa=?";
            int id_mesa_ = 0;
            String verificarpedidomesaexistente = "select 1 from pedido where id_mesa =?";
            String creacionpedido = "insert into pedido(actividad, pago, id_mesa, estado) values (?,?,?,?)";
            String extraeridPedido = "select id_pedido from pedido where id_mesa = ?";
            int id_pedido = 0;
            String enlazarclientepedido = "update clientes set id_pedido = ? where id_mesa = ?";

            try (Connection conn = Conexion.getConexion(); PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setInt(1, Integer.parseInt(Field_Mesa_ID.getText()));

                try (ResultSet rs = stmt.executeQuery()) {
                    if (rs.next()) {
                        id_mesa_ = rs.getInt("id_mesa");
                    }
                }

            } catch (SQLException e) {
                System.out.println("ERROR: " + e.getMessage());
            }
            try (Connection conn = Conexion.getConexion(); PreparedStatement stmt = conn.prepareStatement(verificarpedidomesaexistente)) {
                stmt.setInt(1, id_mesa_);
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Mesa Ocupada");
                } else {
                    try (Connection conn0 = Conexion.getConexion(); PreparedStatement stmt0 = conn0.prepareStatement(creacionpedido)) {

                        stmt0.setBoolean(1, true);
                        stmt0.setNull(2, java.sql.Types.NUMERIC);
                        stmt0.setInt(3, id_mesa_);
                        stmt0.setBoolean(4, false);
                        stmt0.execute();

                    } catch (SQLException e) {
                        System.out.println("ERROR: " + e.getMessage());
                    }

                    try (Connection conn1 = Conexion.getConexion(); PreparedStatement stmt1 = conn1.prepareStatement(extraeridPedido)) {
                        stmt1.setInt(1, Integer.parseInt(Field_Mesa_ID.getText()));

                        try (ResultSet rs1 = stmt1.executeQuery()) {
                            if (rs1.next()) {
                                id_pedido = rs1.getInt("id_pedido");
                            }
                        }

                    } catch (SQLException e) {
                        System.out.println("ERROR: " + e.getMessage());
                    }
                    try (Connection conn2 = Conexion.getConexion(); PreparedStatement stmt2 = conn2.prepareStatement(enlazarclientepedido)) {
                        stmt2.setInt(1, id_pedido);
                        stmt2.setInt(2, id_mesa_);
                        stmt2.execute();

                    } catch (SQLException e) {
                        System.out.println("ERROR: " + e.getMessage());
                    }

                }

            } catch (SQLException e) {
                System.out.println("Mensaje: " + e);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor válido");
        }
    }//GEN-LAST:event_Boton_Asignar_MesaActionPerformed

    private void Boton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BuscarActionPerformed
        // TODO add your handling code here:
        try {
            int val = Integer.parseInt(Field_DNI.getText());
            Tabla_Clientes.setModel(admin.consultarcliente(Integer.parseInt(Field_DNI.getText())));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor válido");
        }
    }//GEN-LAST:event_Boton_BuscarActionPerformed

    private void Listar_Registrar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_Registrar_ClienteActionPerformed
        // TODO add your handling code here:
        Field_DNI.setText("");
        Tabla_Clientes.setModel(admin.observarclientes());
    }//GEN-LAST:event_Listar_Registrar_ClienteActionPerformed

    private void Boton_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_InsertarActionPerformed
        try {
            int dni = Integer.parseInt(Field_DNI.getText());
            if (Field_DNI.getText().trim().length() != 8) {
                JOptionPane.showMessageDialog(null, "Longitud inválida");
            } else {
                String nombre = api.obtenerNombre(api.lecturaderespuesta(api.crearConexion(Field_DNI.getText())));
                String apellido_materno = api.obtenerApellidoMaterno(api.lecturaderespuesta(api.crearConexion(Field_DNI.getText())));
                String apellido_paterno = api.obtenerApellidoPaterno(api.lecturaderespuesta(api.crearConexion(Field_DNI.getText())));
                if (nombre.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Dni no existe");
                } else {
                    try {
                        admin.insertarCliente(Integer.parseInt(Field_DNI.getText()), nombre,
                            apellido_paterno, apellido_materno);
                        Tabla_Clientes.setModel(admin.observarclientes());
                        JOptionPane.showMessageDialog(null, "Cliente Agregado");
                    } catch (Exception e) {
                        String mensaje = e.getMessage();
                        if (mensaje != null && mensaje.contains("Cliente ya existe")) {
                            JOptionPane.showMessageDialog(null, " El cliente ya está registrado.");
                        } else {
                            JOptionPane.showMessageDialog(null, " Error al insertar cliente:\n" + mensaje);
                        }
                    }

                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero válido");
        }
        Tabla_Clientes.setModel(admin.observarclientes());
    }//GEN-LAST:event_Boton_InsertarActionPerformed

    private void Field_DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_DNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_DNIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Asignar_Mesa;
    private javax.swing.JButton Boton_Buscar;
    private javax.swing.JButton Boton_Insertar;
    private javax.swing.JButton Boton_Mesa_RegistrarCliente;
    private javax.swing.JButton Boton_Retorno;
    private javax.swing.JTextField Field_DNI;
    private javax.swing.JTextField Field_Mesa_ID;
    private javax.swing.JButton Listar_Registrar_Cliente;
    private javax.swing.JLabel Mensaje_Error_ActivarPedido;
    private javax.swing.JLabel Mensaje_Error_Cliente;
    private javax.swing.JTable Tabla_Clientes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
