/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JFrame;

/**
 *
 * @author Arana
 */
public class PanelAdmin extends javax.swing.JFrame {

    FormMenu_Administrador m = new FormMenu_Administrador();
    Form_Mesas_Administrador mesas = new Form_Mesas_Administrador();
    Form_Cocina_Administrador cocina = new Form_Cocina_Administrador();

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Admin_Menu = new javax.swing.JButton();
        Boton_Administrador_Mesa = new javax.swing.JButton();
        Admin_Cocina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Admin_Menu.setText("Admin_Menu");
        Admin_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_MenuActionPerformed(evt);
            }
        });

        Boton_Administrador_Mesa.setText("Admin_Mesa");
        Boton_Administrador_Mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Administrador_MesaActionPerformed(evt);
            }
        });

        Admin_Cocina.setText("Admin_Cocina");
        Admin_Cocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_CocinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admin_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Boton_Administrador_Mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(Admin_Cocina, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Admin_Cocina, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(Boton_Administrador_Mesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Admin_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_MenuActionPerformed
        // TODO add your handling code here:
        m.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        m.setVisible(true);
        m.setEnabled(true);
        m.setResizable(false);
    }//GEN-LAST:event_Admin_MenuActionPerformed

    private void Boton_Administrador_MesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Administrador_MesaActionPerformed
        // TODO add your handling code here:
        mesas.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mesas.setVisible(true);
        mesas.setEnabled(true);
        mesas.setResizable(false);
    }//GEN-LAST:event_Boton_Administrador_MesaActionPerformed

    private void Admin_CocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_CocinaActionPerformed
        // TODO add your handling code here:
        cocina.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        cocina.setVisible(true);
        cocina.setEnabled(true);
        cocina.setResizable(false);
    }//GEN-LAST:event_Admin_CocinaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_Cocina;
    private javax.swing.JButton Admin_Menu;
    private javax.swing.JButton Boton_Administrador_Mesa;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
